name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up environment variables
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Build and tag the client Docker image
      run: |
        cd client
        docker build . --file Dockerfile --tag arunkrizz/graphql_nesttests-client
        docker tag arunkrizz/graphql_nesttests-client arunkrizz/graphql_nesttests-client:${{ env.TIMESTAMP }}
    - name: Build and tag the server Docker image
      run: |
        cd backend
        docker build . --file Dockerfile --tag arunkrizz/graphql_nesttests-server
        docker tag arunkrizz/graphql_nesttests-server arunkrizz/graphql_nesttests-server:${{ env.TIMESTAMP }}
    - name: Push the client Docker image
      run: |
        docker push arunkrizz/graphql_nesttests-client
        docker push arunkrizz/graphql_nesttests-client:${{ env.TIMESTAMP }}
    - name: Push the server Docker image
      run: |
        docker push arunkrizz/graphql_nesttests-server
        docker push arunkrizz/graphql_nesttests-server:${{ env.TIMESTAMP }}
